---
new_page_extension: html
auto_deploy: true
admin_path: admin
sections:
- type: document 
  label: Property Details + Photos
  path: _data/home-info.json
  templates: property-info-template
- type: document
  label: Agent Details
  path: _data/agent.json
  templates: agent-info-template
- type: document
  label: Media
  path: _data/media.json
  templates: media
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
